CREATE TABLE payment (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        amount NUMERIC(10, 2) NOT NULL,
        method VARCHAR(50) NOT NULL,
        status VARCHAR(50) NOT NULL,
        created_at TIMESTAMP NOT NULL,
        processed_at TIMESTAMP,

        CONSTRAINT fk_payment_orders
                FOREIGN KEY (order_id)
                REFERENCES orders(id)
);